"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.camelCase = exports.isCallable = exports.isFunction = exports.isString = exports.upperFirst = exports.walkSync = exports.isDirectory = void 0;
const fs = require('fs');
const path = require('path');
const isCallable = require('is-callable');
exports.isCallable = isCallable;
const camelCase = require('camelcase');
exports.camelCase = camelCase;
const isDirectory = (dir) => fs.lstatSync(dir).isDirectory();
exports.isDirectory = isDirectory;
const walkSync = (file) => (0, exports.isDirectory)(file) ? fs.readdirSync(file).map(f => (0, exports.walkSync)(path.join(file, f))) : file;
exports.walkSync = walkSync;
const upperFirst = (s) => s.charAt(0).toUpperCase() + s.slice(1);
exports.upperFirst = upperFirst;
const isString = s => typeof s === 'string';
exports.isString = isString;
const isFunction = f => typeof f === 'function';
exports.isFunction = isFunction;
//# sourceMappingURL=utils.js.map